image: debian:bullseye-slim

stages: 
  - static analysis 
  - build
  - test

.variables:
  default_variables: &default_variables 
    CMAKE_INSTALL_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/cmake"
    CMAKE_BUILD_DIR: "${CI_PROJECT_DIR}/build"
    CMAKE_BUILD_TYPE: Release 
    CXX: g++
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    HESTIA_BUILD_TESTS: "OFF" 
    HESTIA_BUILD_DOCUMENTATION: "OFF"
    HESTIA_DOC_DIR: ""
    HESTIA_BUILD_THREADS: "4"
    HESTIA_DEPS: "${CI_PROJECT_DIR}/infra/deps/hestia-deps-debian-11"
.snippets: 
  - &install_dependencies
    apt-get update -qqy
    && apt-get install --no-install-recommends -qqy $(cat ${HESTIA_DEPS}.dev)
    && ${CI_PROJECT_DIR}/infra/scripts/bootstrap_cmake.sh $CMAKE_INSTALL_CACHE_DIR
  - &configure 
    mkdir -p "${CMAKE_BUILD_DIR}"
    && pushd "${CMAKE_BUILD_DIR}"
    && (
      set -x;
      $CMAKE_INSTALL_CACHE_DIR/bin/cmake ${CI_PROJECT_DIR} 
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" 
      -DCMAKE_EXPORT_COMPILE_COMMANDS="${CMAKE_EXPORT_COMPILE_COMMANDS}" 
      -DCMAKE_CXX_COMPILER="${CXX}" 
      -DHESTIA_WITH_PHOBOS=OFF
      -DHESTIA_BUILD_TESTS="${HESTIA_BUILD_TESTS}"
    )
    && popd
  - &build 
    make -C "${CMAKE_BUILD_DIR}" -j $HESTIA_BUILD_THREADS
  - &test
    make -C "${CMAKE_BUILD_DIR}" test -j $HESTIA_BUILD_THREADS

.cache:
  cmake_install_cache: &cmake_install_cache
    key: "cmake_3.26.3"
    paths:
      - .cache/cmake/

.artifacts:
  build_artifacts: &build_artifacts
    name:  "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - build/
    expire_in: 30 min

.default_job: &default_job 
  tags: 
    - docker
  variables:
    <<: *default_variables 
  before_script: 
    - *install_dependencies
  script: 
    - *configure 
    - *build 
  cache:
    <<: *cmake_install_cache

Format: 
  <<: *default_job
  stage: static analysis
  before_script: 
    - apt-get update -qqy 
      && apt-get install --no-install-recommends -qqy $(cat ${HESTIA_DEPS}.format)
  script: 
    - ./infra/scripts/run_format.sh
      && git status 
      && git diff-index --quiet HEAD 
      || { echo "This commit contains unformatted files! Run tools/run_format.sh to format them correctly."; false; }

Lint: 
  <<: *default_job
  stage: static analysis
  variables:
    <<: *default_variables
    CMAKE_BUILD_TYPE: Debug
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    CXX: clang++
    HESTIA_BUILD_TESTS: "ON" 
  before_script:
    - *install_dependencies
    - apt-get install --no-install-recommends -qqy $(cat ${HESTIA_DEPS}.lint) clang clang-tidy
    - *configure
    - *build 
  script:
    - ./infra/scripts/run_lint.sh "${CMAKE_BUILD_DIR}"


#Documentation:
#   <<: *default_job
#   stage: build 
#   variables:
#       <<: *default_variables
#       HESTIA_BUILD_DOCUMENTATION: "ON"
#        HESTIA_DOC_DIR: ../../doc/parser/src
#    script:
#        - apt-get install --no-install-recommends -y
#            cmake
#            git
#            doxygen
#            graphviz
#            texlive texlive-font-utils
#        - *configure
#        - make -C build/doc
#            && git status
#            && git diff-index --quiet HEAD
#            || { echo "This commit contains changes to the documentation! Run doxygen-XML-parser on the project update the documentation."; false; }


Debug:
  <<: *default_job
  stage: build
  variables:
    <<: *default_variables
    CMAKE_BUILD_TYPE: Debug
    HESTIA_BUILD_TESTS: "ON" # Ensure all code is seen by Debug build

Release:
  <<: *default_job
  stage: build


Unit_test:
  <<: *default_job
  stage: test
  dependencies: 
    - Release
  variables:
    <<: *default_variables
    CMAKE_BUILD_TYPE: Release
    HESTIA_BUILD_TESTS: "ON"
  script:
    - *configure
    - *build
    - *test