image: rockylinux:8

stages:   
  - static analysis 
  - build
  - test

# Hestia CI variables
.variables:
  default_variables: &default_variables 
    CMAKE_INSTALL_CACHE_DIR: "${CI_PROJECT_DIR}/.cache"
    CMAKE_BUILD_DIR: "${CI_PROJECT_DIR}/build"
    CMAKE_BUILD_TYPE: Release 
    CXX: g++
    C: gcc
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    HESTIA_BUILD_TESTS: "OFF" 
    HESTIA_BUILD_DOCUMENTATION: "OFF"
    HESTIA_DOC_DIR: ""
    HESTIA_DEPS: "${CI_PROJECT_DIR}/infra/deps/rocky8"

# Hestia CI code snippets
.snippets: 
  - &update_distro
    yum check-update -q || true;
    yum update -qy;
    yum install -qy epel-release;
    yum config-manager -q --set-enabled powertools;
  - &install_base_dependencies
    yum install -qy $(cat ${HESTIA_DEPS}/base);
    ${CI_PROJECT_DIR}/infra/scripts/bootstrap_cmake.sh $CMAKE_INSTALL_CACHE_DIR;
  - &install_motr
    yum install -qy ${CI_PROJECT_DIR}/motr-rpms/linux/*/isa-l-2.30.0*.$(arch).rpm;
    yum install -qy ${CI_PROJECT_DIR}/motr-rpms/linux/*/cortx-motr-2.0.0*.$(arch).rpm;
    yum install -qy ${CI_PROJECT_DIR}/motr-rpms/linux/*/cortx-motr-devel-2.0.0*.$(arch).rpm;
  - &configure 
    mkdir -p "${CMAKE_BUILD_DIR}"
    && pushd "${CMAKE_BUILD_DIR}"
    && (
      set -x;
      $CMAKE_INSTALL_CACHE_DIR/bin/cmake ${CI_PROJECT_DIR} 
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" 
      -DCMAKE_EXPORT_COMPILE_COMMANDS="${CMAKE_EXPORT_COMPILE_COMMANDS}" 
      -DCMAKE_CXX_COMPILER="${CXX}" 
      -DHESTIA_WITH_PHOBOS=OFF
      -DHESTIA_BUILD_TESTS="${HESTIA_BUILD_TESTS}"
    )
    && popd
  - &build 
    make -C "${CMAKE_BUILD_DIR}" -j$(nproc)
  - &test
    make -C "${CMAKE_BUILD_DIR}" CTEST_OUTPUT_ON_FAILURE=1 test -j$(nproc)

.cache:
  cmake_install_cache: &cmake_install_cache
    key: "cmake_3.26.3"
    paths:
      - .cache/cmake/

.artifacts:
  build_artifacts: &build_artifacts
    name:  "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - build/
    expire_in: 30 min

.default_job: &default_job 
  tags: 
    - docker
  variables:
    <<: *default_variables 
  before_script: 
    - *update_distro
    - *install_base_dependencies
  script: 
    - *configure 
    - *build 
  cache:
    <<: *cmake_install_cache

motr_rpm_download:
  tags:
    - docker
  stage: .pre
  image: alpine
  script:
    - 'wget -qO rpms.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://git.ichec.ie/api/v4/projects/418/jobs/artifacts/motr-rpm-builds/download?job=motr_rpm_build"'
    - unzip -q rpms.zip && rm -f rpms.zip
  artifacts:
    expire_in: 1 hour
    paths:
      - motr-rpms/

# Hestia CI Jobs
motr install test:
  <<: *default_job
  stage: static analysis
  dependencies:
    - motr_rpm_download
  before_script: 
    - *update_distro
  script:
    - *install_motr

Format: 
  <<: *default_job
  stage: static analysis
  dependencies: []
  before_script: 
    - *update_distro
    - yum install -qy $(cat ${HESTIA_DEPS}/format)
  script: 
    - ./infra/scripts/run_format.sh
      && git status 
      && git diff-index --quiet HEAD 
      || { echo "This commit contains unformatted files! Run tools/run_format.sh to format them correctly."; false; }

Lint: 
  <<: *default_job
  stage: static analysis
  dependencies: []
  variables:
    <<: *default_variables
    CMAKE_BUILD_TYPE: Debug
    CMAKE_EXPORT_COMPILE_COMMANDS: "ON"
    CXX: clang++
    C: clang
    HESTIA_BUILD_TESTS: "ON" 
  before_script:
    - *update_distro
    - *install_base_dependencies
    - yum install -qy $(cat ${HESTIA_DEPS}/lint)
    - *configure
    - *build 
  script:
    - ./infra/scripts/run_lint.sh "${CMAKE_BUILD_DIR}"


#Documentation:
#   <<: *default_job
#   stage: build 
#   variables:
#       <<: *default_variables
#       HESTIA_BUILD_DOCUMENTATION: "ON"
#        HESTIA_DOC_DIR: ../../doc/parser/src
#    script:
#        - apt-get install --no-install-recommends -y
#            cmake
#            git
#            doxygen
#            graphviz
#            texlive texlive-font-utils
#        - *configure
#        - make -C build/doc
#            && git status
#            && git diff-index --quiet HEAD
#            || { echo "This commit contains changes to the documentation! Run doxygen-XML-parser on the project update the documentation."; false; }

Release:
  <<: *default_job
  stage: build

Unit_test:
  <<: *default_job
  stage: test
  dependencies: 
    - Release
  variables:
    <<: *default_variables
    CMAKE_BUILD_TYPE: Debug
    HESTIA_BUILD_TESTS: "ON"
  before_script:
    - *update_distro
    - *install_base_dependencies
    - yum install -qy $(cat ${HESTIA_DEPS}/test)
  script:
    - *configure
    - *build
  script:
    - *test