image: rockylinux:8

stages:   
  - motr


.base_motr_rpm_build: &base_motr_rpm_build 
  stage: motr
  tags: 
    - docker
  variables:
    DEPS_DIR: "${CI_PROJECT_DIR}/infra/deps/rocky8"
    MOTR_BUILD_DIR: "${CI_PROJECT_DIR}/motr_superbuild"
    MOTR_RPM_DIR: "${CI_PROJECT_DIR}/motr-rpms/${CI_RUNNER_EXECUTABLE_ARCH}"
  before_script:
    - yum -q check-update || true # Returns exit code 100 if updates exist
    - yum update -qy
    - yum install -qy epel-release
    - yum config-manager -q --set-enabled powertools
    - yum install -qy $(cat ${DEPS_DIR}/motr-rpm)
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --no-cache-dir $(cat ${DEPS_DIR}/motr-rpm-pip)
  script:
    - ${CI_PROJECT_DIR}/infra/scripts/build_motr.sh
  artifacts:
    name: "motr-rpms"
    expire_in: 1 month
    paths:
      - "${CI_PROJECT_DIR}/motr-rpms/${CI_RUNNER_EXECUTABLE_ARCH}"

motr_rpm_build:
  <<: *base_motr_rpm_build
  when: manual

arm_motr_rpm_build:
  <<: *base_motr_rpm_build
  when: manual
  tags:
    - docker
    - arm