---
# Handlers for Hestia
- name: "Start Hestia"
  ansible.builtin.service:
    name: hestiad
    enabled: true
    state: started
  listen: "start_hestia"

- name: "Restart Hestia"
  ansible.builtin.service:
    name: hestiad
    status: restarted
  listen: "restart_hestia"