---
- name: Common Setup
  ansible.builtin.import_role: 
    name: hestia_common

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: latest

- name: Start Redis
  ansible.builtin.service:
    name: redis
    enabled: true
    state: started

- name: Configure Hestia
  ansible.builtin.template:
    src: hestia-controller.yaml.j2
    dest: "{{ hestia_config_dir }}/hestiad.yaml"
  notify: 
    - 'start_hestia'