# Testing setup Hestia variables

# URL of IOSEA repository
iosea_repo_url: 'http://hestia_repo'

# Hestia Configuration Directory
hestia_config_dir: '/etc/hestia'

# Port Hestia servers run on
hestia_server_port: 8080

# Tiers
hestia_hsm_tiers: ["0", "1", "2", "3", "4"]

# To allow to run on non-systemd environments
hestia_as_service: false

# Give more debug information
hestia_verbosity: info