---
# Deploy Hestia locally on a test cluster with controller and worker nodes
- hosts: controllers
  roles:
    - hestia_controller_node

- hosts: workers
  roles:
    - hestia_worker_node

- hosts: clients
  roles:
    - hestia_common

# Execute Basic Testing on Setup
- name: Test Hestia
  hosts: controllers:workers

  tasks:
  - ansible.builtin.shell: 'curl localhost:8080/api/v1/ping'