hestia:
  children:
    controller_group_0:

controller_group_0:
  children:
    workers:
    controllers:

controllers:
  hosts:
    hestia-controller:
workers:
  hosts:
    hestia-worker-phobos:
    hestia-worker-motr: 