hestia:
  children:
    controller_group_0:

controller_group_0:
  children:
    workers:
    controllers:

controllers:
  hosts:
    hestia-controller:

workers:
  children:
    motr:
    phobos:

motr-workers:
  hosts:
    hestia-worker-motr: 

phobos-workers:
  hosts:
    hestia-worker-phobos: