hestia:
  children:
    controller_group_0:
    clients:

clients:
  hosts:
    hestia_client:

controller_group_0:
  children:
    workers:
    controllers:

controllers:
  hosts:
    hestia_controller_0:

workers:
  children:
    file_hsm_workers:
    # motr_workers:
    # phobos_workers:

file_hsm_workers:
  hosts:
    hestia_worker_0:
      hestia_object_store_backends:
        - backend_type: "file_hsm"
          tier_names: ["0", "1"]
    hestia_worker_1:
      hestia_object_store_backends:
        - backend_type: "file_hsm"
          tier_names: ["2", "3", "4"]

# Mock Motr & Phobos Examples

# motr_workers:
#   hosts:
#     hestia_worker_motr:
#       hestia_node_backends:
#         - backend_type: "mock_motr"
#           tier_names: ["0"]
#           config:
#             tier_info:
#               - name: "name0"
#                 identifier: "identifier0"
#                 description: "test tier"

# phobos_workers:
#   hosts:
#     hestia_worker_phobos:
#       hestia_node_backends:
#         - backend_type: "mock_phobos"
#           tier_names: ["0"]
