---
- name: Add IOSEA Repo
  ansible.builtin.yum_repository:
    name: iosea
    description: IOSEA YUM repo
    baseurl: "{{ iosea_repo_url }}"
    gpgcheck: false

- name: Install Hestia
  ansible.builtin.yum:
    name: hestia
    state: latest

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true # Ensure our hestia service unit is loaded