---
- import_role: 
    name: hestia_common

- name: Configure Hestia
  ansible.builtin.template:
    src: hestia-worker.yaml.j2
    dest: "{{ hestia_config_dir }}/hestiad.yaml"
  become: true
  notify: 
    - "start_hestia"
