---
- include_role: 
    name: hestia_common
    public: true

- name: Configure Hestia
  ansible.builtin.template:
    src: hestia-worker.yml.j2
    dest: "{{ hestia_config_dir }}/hestiad.yml"
  notify: 
    - Start Hestia